# Generated by Django 4.2.23 on 2025-07-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pic_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sic_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('night_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('solo_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cross_country_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_takeoffs', models.IntegerField(default=0)),
                ('day_landings', models.IntegerField(default=0)),
                ('night_takeoffs', models.IntegerField(default=0)),
                ('night_landings', models.IntegerField(default=0)),
                ('actual_instrument_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('simulated_instrument_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pilot_comments', models.TextField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotlog.aircraft')),
                ('arrival_airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='pilotlog.airfield')),
                ('departure_airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='pilotlog.airfield')),
            ],
        ),
    ]
